---
efiBootLoader: "grub"
kernel: "/vmlinuz"
img: "/initramfs.img"
timeout: 3
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootloaderId: "GentooVM"
installEFIFallback: true
