---
mountOptions:
    default: defaults,noatime
    btrfs: defaults,noatime,compress=zstd
    ext4: defaults,noatime

ssdExtraMountOptions:
    ext4: discard
    btrfs: discard=async

crypttabOptions: luks
