---
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 512M
efiSystemPartitionName: EFI

# BIOS boot partition for GPT + BIOS mode
# Calamares handles this, but we also handle it in postinstall
userSwapChoices:
    - none

drawNestedPartitions: false
alwaysShowPartitionLabels: true
allowManualPartitioning: true

initialPartitioningChoice: erase
initialSwapChoice: none

defaultPartitionTableType: gpt

defaultFileSystemType: "ext4"
availableFileSystemTypes: ["ext4"]
