---
services:
  - name: "NetworkManager"
    mandatory: true
  - name: "lightdm"
    mandatory: true
  - name: "systemd-zram-setup@zram0"
    mandatory: false
  - name: "qemu-guest-agent"
    mandatory: false

targets:
  - name: "graphical"
    mandatory: true
