---
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false

requirements:
    requiredStorage: 15.0
    requiredRam: 2.0
    internetCheckUrl: ""
    check:
        - storage
        - ram
    required:
        - storage
        - ram

languageIcon: languages
